import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-presentation',
  standalone: true,
  imports: [RouterModule],
  templateUrl: './presentation.component.html',
  styleUrl: './presentation.component.scss',
})
export class PresentationComponent {
  name: string = 'Jesus David Mejia';
  carrers: string[] = [
    'Full Stack Developer',
    'Ingeniero de Sistemas',
    'Especialista en Procesos',
    'de Desarrollo de Software',
  ];
  presentation: string =
    'Con respecto a mi persona, tengo 24 años soy Ingeniero en Sistemas y quisiera destacar, que soy una persona que ama y le apasiona lo que hace buscando con ello siempre comprometerse al máximo en cada uno de sus proyectos y que, a su vez, disfruta de trabajar en equipo, compartir sus conocimientos y aprender de igual manera de los conocimientos de los demás. En mi experiencia profesional como desarrollador web, he tenido la oportunidad de trabajar con personas altamente capacitadas en los lenguajes de programación de los diferentes proyectos, lo cual he sabido aprovechar al máximo para mejorar y estimular mis habilidades y conocimientos como profesional en la parte de Frontend y Backend.';
  technologies: string[] = [
    'HTML',
    'CSS',
    'SCSS',
    'Javascript',
    'Typescript',
    'NPM',
    'Angular',
    'Components',
    'Services',
    'Directives',
    'Pipes',
    'Guards',
    'Interceptors',
    'Templates',
    'Data Binding',
    'Reactive Forms',
    'RxJS',
    'NgRx',
    'HTTP Client',
    'Angular Unit Test',
    'Angular Integration Test',
    'Angular E2E',
    'Jasmine',
    'Karma',
    'Bootstrap',
    'NG-Bootstrap',
    'Angular CDK',
    'Angular Material',
    'PrimeNG',
    'Tailwind',
    'Preline',
    'NodeJS',
    'Express',
    'NVM',
    'TS-Node',
    'Nodemon',
    'ORM',
    'Prisma',
    'Sequealize',
    'Async/Await',
    'Promises',
    'Files',
    'Routes',
    'Auth',
    'JWT',
    'Middlewares',
    'Emails',
    'Cron Jobs',
    'Node Unit Test',
    'Node Integration Test',
    'Node E2E',
    'Jest',
    'CORS',
    'Swagger',
    'APIs',
    'Encryption',
    'Segurity',
    'Java',
    'Java SE',
    'Spring Boot',
    'Spring Web',
    'Spring Data JPA',
    'DTO',
    'Repository',
    'GitHub',
    'GitHub Actions',
    'GitLab',
    'Workflows',
    'Pipeline',
    'CI/CD',
    'Docker',
    'SQL',
    'MySQL',
    'Postgres',
    'MongoDB',
  ];
  technologiesMobile: string[] = [
    'HTML',
    'CSS',
    'SCSS',
    'Javascript',
    'Typescript',
    'Angular',
    'RxJS',
    'NgRx',
    'Angular Testing',
    'Bootstrap',
    'NG-Bootstrap',
    'Angular CDK',
    'Angular Material',
    'PrimeNG',
    'Tailwind',
    'NodeJS',
    'Express',
    'Nodemon',
    'TS-Node',
    'ORM',
    'Async/Await',
    'Promises',
    'Files',
    'Auth',
    'JWT',
    'Emails',
    'Cron Jobs',
    'Node Testing',
    'Jest',
    'CORS',
    'Swagger',
    'Java',
    'Java SE',
    'Spring Boot',
    'Spring Web',
    'Spring Data JPA',
    'GitHub',
    'GitHub Actions',
    'GitLab',
    'Workflows',
    'Pipeline',
    'CI/CD',
    'Docker',
    'SQL',
    'MySQL',
    'Postgres',
    'MongoDB',
  ];
}
